### ISSUE TITLE
nakka - login not successful after call with autodarts-extern

### ISSUE THREAD

**Issue by drcliff** [lbormann/autodarts-extern#2]
Hi,

i have the issue, that i am not able to log in after calling the nakka homepage via autodarts-extern (neither via autodarts-external, nor via console command). I have the same behavior running it via Windows and Q4OS linux system.
I get the naka startuppage shown in chrome browser, but after choosing "google" to login with google account and entering my email address, there is the attached message shown.
![Nakka Google message](https://github.com/lbormann/autodarts-extern/assets/73689426/d4146448-fffc-4c76-9c0f-6a852dbd8a10)

Anybody have any idea?

Thank you in advance.
Chris

**Comment by lbormann** [comment]
> Hi,
> 
> i have the issue, that i am not able to log in after calling the nakka homepage via autodarts-extern (neither via autodarts-external, nor via console command). I have the same behavior running it via Windows and Q4OS linux system. I get the naka startuppage shown in chrome browser, but after choosing "google" to login with google account and entering my email address, there is the attached message shown. ![Nakka Google message](https://private-user-images.githubusercontent.com/73689426/294046837-d4146448-fffc-4c76-9c0f-6a852dbd8a10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTI0MDcsIm5iZiI6MTcwNTI5MjEwNywicGF0aCI6Ii83MzY4OTQyNi8yOTQwNDY4MzctZDQxNDY0NDgtZmZmYy00Yzc2LTljMGYtNmE4NTJkYmQ4YTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA0MTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNDI0ZDdhYTUwZjQ1ZmY2NWU2YjlmMmYzZDVkY2I1ZDcwYzZlNTMwODQ3YjQ3NzEyYmE4ZjE3ZWE1NTVkNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZVF6aRSHFI6x8pHWXlgVVz7ApOOIN-J9Cvt63iwT8wc)
> 
> Anybody have any idea?
> 
> Thank you in advance. Chris

Yes, this is a known issue. Please try other auth providers like twitter (X)
